import { chromium } from "playwright";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const page = await ctx.newPage();
await page.goto("http://127.0.0.1:3060/", { waitUntil: "networkidle" });
await page.evaluate(() => document.fonts && document.fonts.ready);
await page.waitForTimeout(1500);
await page.addStyleTag({ content: ".rv{opacity:1!important;transform:none!important}" });
await page.waitForTimeout(500);
await page.screenshot({ path: "compare-out/v6-full.png", fullPage: true });
console.log("ok");
await browser.close();
